# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fba37c2d749627a634fbe2919a656819e375c08702d1025d0d76862ebec31ce713e0a9d98ec447e61b155592da3bdcc5026a00f5f01a0251aade2c1afde93b02

test:
  secret_key_base: 65a92f54e7ccbe573960355fffc22c38022e4aff3b6b65a42e6fb86b5b9f6c22e42a63a43c4b3941c3de3da57a6e2197edee32a7f2bb5fb1550847044f62995d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
